version: '3.8'

services:
  secure-app:
    image: light-audit:v1
    networks:
      - private-network

  database:
    image: redis:7-alpine
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
