name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  construir-escanear-desplegar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/execute-app:latest .

      - name: Escaneo de Seguridad (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/execute-app:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL'

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/execute-app:latest
